### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by klonuo** [transpect/docx2hub#7] opened 2016-09-21 12:00 UTC
Hi,

I followed these instructions: http://transpect.github.io/getting-started.html

While running:

`./calabash/calabash.sh -o result=test1.xml docx2hub/xpl/docx2hub.xpl docx=test1.docx`

on a sample docx containing just 3 pages, it took about 15min and 100% CPU to get me to error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:310), pid=859, tid=0x00007fb7ff990700
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: /home/klo/trans_project/core or core.859
#
# An error report file with more information is saved as:
# /home/klo/trans_project/hs_err_pid859.log
[thread 140428747605760 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
./calabash/calabash.sh: line 126:   859 Aborted                 (core dumped) $JAVA -cp "$CLASSPATH" -Dfile.encoding=UTF-8 "-Dxml.catalog.files=$CATALOGS" -Dxml.catalog.staticCatalog=1 -Duser.language=$UI_LANG $SYSPROPS -Xmx$HEAP -Xss1024k com.xmlcalabash.drivers.$DRIVER -Xtransparent-json -E org.xmlresolver.Resolver -U org.xmlresolver.Resolver $SAXON_PROCESSOR -c $CFG $PIPERACK_PORT "$@"
```

Are there some other prerequisites not mentioned in the guide?

**Comment by gimsieke** [comment] 2016-09-21 12:06
If you are using the most recent version of docx2hub, there is an additional requirement of https://github.com/transpect/htmlreports as a submodule (and as a `nextCatalog` entry in xmlcatalog/catalog.xml). But then the error should more read like in https://github.com/transpect/transpect.github.io/issues/1
Can you send [us](mailto:letexml@le-tex.de) the docx file?

**Comment by klonuo** [comment] 2016-09-21 12:58
Hi, thanks for your prompt reply.
I installed new submodule and updated catalog, however I still get the error.
I send sample file as requested.

**Comment by mkraetke** [comment] 2016-09-21 14:58
Concerning the missing htmlreports submodule, I've recently updated the getting started guide.

**Comment by gimsieke** [comment] 2019-11-10 15:54
Unable to reproduce, I’m closing it. Feel free to reopen it when you have a snapshot of your setup available for us to download.

**Closed as completed by gimsieke** 2019-11-10 15:54 UTC
Labels: wontfix
